### ISSUE TITLE
Bounds of sin/cos

### ISSUE THREAD

**Issue by chacha21** [fredrik-johansson/arb#231] opened 2018-07-14 15:47 UTC
Hello,

I have just tested the behaviour of arblib for sin(exp(90)).
I expected the uncertainty to explode, resulting in [-1;1].
The answer is funny : [-2.995843;1.004157]
Is there a reason why arb would not clip itself the range of sin/cos to [-1;1] ?

`arb_t a;
  arb_init(a);
  arb_set_d(a, 90);
  arb_exp(a, a, 128);
  arb_sin(a, a, 128);
  arf_t inff;
  arf_t supf;
  arf_init(inff);
  arf_init(supf);
  arb_get_lbound_arf(inff, a, 128);
  arb_get_ubound_arf(supf, a, 128);
  printf("[%f;%f]\n", arf_get_d(inff, ARF_RND_NEAR), arf_get_d(supf, ARF_RND_NEAR));`

**Comment by fredrik-johansson** [comment] 2018-07-14 15:59
No reason other than lack of development time. There is code sitting on my laptop for improving the bounds of sin and cos, but it's not complete yet.

**Comment by fredrik-johansson** [comment] 2018-07-19 17:46
I have merged code that produces tighter enclosures for sine and cosine and also adjusts the output precision based on the input precision. The new code is rather complex (to avoid sacrificing speed) and I will need to do some further testing to make sure it really works as intended before making a new release.

**Closed** 2018-07-22 20:33 UTC
